# Generated by Django 5.2.6 on 2025-10-20 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_standalonetask_completed_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneTaskEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('intent', models.CharField(choices=[('failure', 'Failure'), ('completion', 'Completion')], max_length=20)),
                ('task_issuer', models.BooleanField(default=False)),
                ('task_leader', models.BooleanField(default=False)),
                ('task_assignees', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_configs', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Email Config',
                'verbose_name_plural': 'Task Email Configs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'intent'), name='unique_email_config_per_task_intent')],
            },
        ),
    ]
