# Generated by Django 5.2.6 on 2025-10-22 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_standalonetaskemailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonetask',
            name='completed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_completed_tasks', to='tasks.standalonetaskstatus'),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='failed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_failed_tasks', to='tasks.standalonetaskstatus'),
        ),
    ]
