# Generated by Django 5.2.6 on 2025-10-14 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projecttaskstatus_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttaskstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_statuses', to='projects.project'),
        ),
    ]
