# Generated by Django 5.2.6 on 2025-10-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_initial'),
        ('projects', '0005_taskstatus_task'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('name', 'task'), name='unique_task_status_per_task'),
        ),
    ]
