# Generated by Django 5.2.6 on 2025-10-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='applied_project_task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks_status', to='projects.projecttaskstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='applied_task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_tasks_status', to='projects.taskstatus'),
        ),
    ]
