# Generated by Django 5.2.6 on 2025-10-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_task_applied_project_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_completed_status', to='projects.taskstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='failed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_failed_status', to='projects.taskstatus'),
        ),
    ]
