# Generated by Django 5.2.6 on 2025-10-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectdiscussionparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdiscussionparticipant',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='taskdiscussionparticipant',
            name='added_at',
        ),
    ]
