# Generated by Django 5.2.6 on 2025-10-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_task_applied_task_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
