# Generated by Django 5.2.7 on 2025-10-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar2', '0001_initial'),
        ('institution', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_calendars', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_events', to='institution.department'),
        ),
        migrations.AddField(
            model_name='event',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_events', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='event',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, related_name='specific_employees_events', to='users.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='calendars', to='calendar2.event'),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_occurrences', to='calendar2.calendar'),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar2.event'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_public_holidays', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='public_holidays',
            field=models.ManyToManyField(blank=True, related_name='calendars', to='calendar2.publicholiday'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoccurrence',
            unique_together={('event', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('institution', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('institution', 'year')},
        ),
    ]
