from django.urls import path
from .views import (
    ChangePasswordAPIView,
    LoginView,
    CustomTokenRefreshView,
    StaffGroupDetailView,
    StaffGroupListCreateView,
    StaffGroupRoleDetailView,
    StaffGroupRoleListCreateView,
    StaffGroupUserDetailView,
    StaffGroupUserListCreateView,
    UserDetailAPIView,
    UserListAPIView,
    VerifyOTPAPIView,
    ResendOTPAPIView,
    RoleListAPIView,
    RoleDetailAPIView,
    PermissionCategoryListAPIView,
    PermissionCategoryDetailAPIView,
    PermissionListAPIView,
    PermissionDetailAPIView,
    UserInstitutionsListAPIView,
    ForgotPasswordAPIView,
    VerifyTokenAPIView,
    ResetPasswordAPIView,
    GoogleAuthURLView,
    GoogleAuthCallbackView,
    UserDetailsWithInstitutions,
    CountryListAPIView,
    ChangeEmailAndResendOTPAPIView,
    LogoutView,
    BranchUsersView,
)


urlpatterns = [
    path("", UserListAPIView.as_view(), name="user-management"),
    path("<int:user_id>/", UserDetailAPIView.as_view(), name="user-detail"),
    path(
        "institutions/",
        UserInstitutionsListAPIView.as_view(),
        name="user-attached-institutions",
    ),
    path(
        "change-email-and-resend-otp/",
        ChangeEmailAndResendOTPAPIView.as_view(),
        name="change-email-and-resend-otp",
    ),
    path("verify-otp/", VerifyOTPAPIView.as_view(), name="verify-otp"),
    path("resend-otp/", ResendOTPAPIView.as_view(), name="resend-otp"),
    path("login/", LoginView.as_view(), name="user-login"),
    path("token/refresh/", CustomTokenRefreshView.as_view(), name="token-refresh"),
    path("logout/", LogoutView.as_view(), name="user-logout"),
    path("role/", RoleListAPIView.as_view(), name="role-list"),
    path("role/<int:role_id>/", RoleDetailAPIView.as_view(), name="role-detail"),
    path(
        "permission-category/",
        PermissionCategoryListAPIView.as_view(),
        name="permission-category",
    ),
    path(
        "permission-category/<int:permission_category_id>",
        PermissionCategoryDetailAPIView.as_view(),
        name="permission-category-detail",
    ),
    path("permission/", PermissionListAPIView.as_view(), name="permission-list"),
    path(
        "permission/<int:permission_d>",
        PermissionDetailAPIView.as_view(),
        name="permission-detail",
    ),
    path("forgot-password", ForgotPasswordAPIView.as_view(), name="forgot-password"),
    path("verify-token", VerifyTokenAPIView.as_view(), name="verify-token"),
    path("reset-password/", ResetPasswordAPIView.as_view(), name="reset-password"),
    # Continue with Google URLs
    path("auth/google/url/", GoogleAuthURLView.as_view(), name="google_auth_url"),
    path(
        "auth/google/callback/",
        GoogleAuthCallbackView.as_view(),
        name="google_auth_callback",
    ),
    path("details/", UserDetailsWithInstitutions.as_view(), name="user-dets"),
    path("countries/", CountryListAPIView.as_view(), name="country-list"),
    path("change-password/", ChangePasswordAPIView.as_view(), name="change-password"),

    path('staff-groups/', StaffGroupListCreateView.as_view(), name='staff-group-list-create'),
    path('staff-groups/<int:pk>/', StaffGroupDetailView.as_view(), name='staff-group-detail'),
    path('staff-group-roles/', StaffGroupRoleListCreateView.as_view(), name='staff-group-role-list-create'),
    path('staff-group-roles/<int:pk>/', StaffGroupRoleDetailView.as_view(), name='staff-group-role-detail'),
    path('staff-group-users/', StaffGroupUserListCreateView.as_view(), name='staff-group-user-list-create'),
    path('staff-group-users/<int:pk>/', StaffGroupUserDetailView.as_view(), name='staff-group-user-detail'),
    path('related-branch-users/<int:pk>/', BranchUsersView.as_view(), name="branch-users"),

]
