# Generated by Django 5.2.6 on 2025-10-18 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_initial'),
        ('projects', '0016_remove_projectdiscussionparticipant_added_at_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('freeze_assignee', models.BooleanField(default=False)),
                ('custom_fields', models.JSONField(blank=True, default=list, null=True)),
                # ('completed_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_completed_tasks', to='projects.taskstatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                # ('failed_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_failed_tasks', to='projects.taskstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
                ('user_manager', models.ForeignKey(blank=True, help_text='Single manager for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_standalone_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standalone Task',
                'verbose_name_plural': 'Standalone Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('request_reason', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('approval_reason', models.TextField(blank=True, null=True)),
                ('new_start_date', models.DateTimeField(blank=True, null=True)),
                ('new_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('color_code', models.CharField(default='#9C9C9C', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'verbose_name': 'Standalone Task Priority',
                'verbose_name_plural': 'Standalone Task Priorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_tasks', to='tasks.standalonetaskpriority'),
        ),
        migrations.CreateModel(
            name='StandaloneTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('color_code', models.CharField(default='#9C9C9C', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_task_statuses', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'verbose_name': 'Standalone Task Status',
                'verbose_name_plural': 'Standalone Task Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='applied_task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_tasks_status', to='tasks.standalonetaskstatus'),
        ),
        migrations.CreateModel(
            name='StandaloneTaskTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'verbose_name': 'Time Sheet',
                'verbose_name_plural': 'Time Sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskDiscussionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('can_send', models.BooleanField(default=False, help_text='If False, user can only view messages.')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_participants', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_task_discussion_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standalone Task Discussion Participant',
                'verbose_name_plural': 'Standalone Task Discussion Participants',
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='task_documents/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'verbose_name': 'Standalone Task Document',
                'verbose_name_plural': 'Standalone Task Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='tasks_stand_task_id_ed8a81_idx')],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('content', models.TextField(help_text='Message content (max 2000 characters)', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('author', models.ForeignKey(blank=True, help_text='User who sent the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_task_messages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='tasks_stand_task_id_a5d00a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskStaffGroupAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('group_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_assigned_group_tasks', to='users.staffgroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_group_assignees', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Standalone Task Staff Group Assignees',
                'constraints': [models.UniqueConstraint(fields=('task', 'group_assigned'), name='unique_standalone_task_staff_group_assignee')],
            },
        ),
        migrations.CreateModel(
            name='StandaloneTaskUserAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='users.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignees', to='tasks.standalonetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='users.profile')),
                ('user_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Standalone Task User Assignees',
                'constraints': [models.UniqueConstraint(fields=('task', 'user_assigned'), name='unique_standalone_task_user_assignee')],
            },
        ),
    ]
