# Generated by Django 5.2.6 on 2025-10-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='standalonetask',
        #     name='completed_status',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_completed_tasks', to='tasks.standalonetaskstatus'),
        # ),
        # migrations.AlterField(
        #     model_name='standalonetask',
        #     name='failed_status',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_failed_tasks', to='tasks.standalonetaskstatus'),
        # ),
        migrations.AlterField(
            model_name='standalonetaskstatus',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_task_statuses', to='tasks.standalonetask'),
        ),
    ]
