# Generated by Django 5.2.7 on 2025-10-13 06:10

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('provider', models.CharField(choices=[('cpanel', 'cPanel'), ('google_workspace', 'Google Workspace'), ('microsoft_365', 'Microsoft 365')], default='cpanel', max_length=20)),
                ('domain', models.CharField(help_text='e.g., example.com', max_length=100)),
                ('format_template', models.CharField(default='{first_name}.{last_name}', help_text='Use placeholders like {first_name}, {last_name}, {initials}, {fullname} (lowercased and sanitized)', max_length=255)),
                ('quota', models.PositiveIntegerField(default=500, help_text='Email quota in MB (applies to cPanel; Google Workspace quotas are managed via Admin Console)')),
                ('port', models.CharField(default='2083', help_text='API port (e.g., 2083 for cPanel HTTPS)', max_length=5)),
                ('admin_email', models.EmailField(blank=True, help_text='Admin email for Google Workspace delegation (e.g., admin@yourdomain.com)', max_length=254, null=True)),
                ('api_url', models.URLField(blank=True, help_text='For cPanel: e.g., https://yourserver.com:2083', null=True)),
                ('api_username', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('webmail_url', models.URLField(blank=True, help_text='Webmail login URL (e.g., https://mail.yourdomain.com for cPanel or https://mail.google.com for Google Workspace)', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('under_creation', 'Under Creation'), ('under_update', 'Under Update'), ('under_deletion', 'Under Deletion'), ('active', 'Active')], default='under_creation', max_length=20)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams')], max_length=50)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('api_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('oauth_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('oauth_refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('tenant_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('content', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_code', models.CharField(max_length=10, unique=True)),
                ('day_name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
