# Generated by Django 5.2.6 on 2025-10-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_completed_status_project_failed_status'),
        ('settings', '0003_taskemailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskemailconfig',
            name='on_completion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskemailconfig',
            name='on_failure',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='taskemailconfig',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_email_config', to='projects.project'),
        ),
    ]
