# Generated by Django 5.2.6 on 2025-10-15 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_initial'),
        ('projects', '0009_project_completed_status_project_failed_status'),
        ('settings', '0005_alter_taskemailconfig_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskemailconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task Email Config', 'verbose_name_plural': 'Task Email Configs'},
        ),
        migrations.AddConstraint(
            model_name='taskemailconfig',
            constraint=models.UniqueConstraint(fields=('project', 'institution'), name='unique_task_email_config_per_project'),
        ),
    ]
