# Generated by Django 5.2.6 on 2025-10-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_taskemailconfig_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskEmailConfig',
        ),
    ]
