# Generated by Django 5.2.7 on 2025-10-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.action'),
        ),
        migrations.AddField(
            model_name='approval',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='approval_documents', to='approval.action'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocument'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='approval_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='approval.approvaldocument'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevelapprovers',
            name='approval_document_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel'),
        ),
        migrations.AddField(
            model_name='approvaldocumentleveloverriders',
            name='approval_document_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='approval.approval'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvaldocumentlevel'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldocumentleveloverriders',
            name='approver_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevelapprovers',
            name='approver_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='approvers',
            field=models.ManyToManyField(related_name='approver_levels', through='approval.ApprovalDocumentLevelApprovers', to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvaldocumentlevel',
            name='overriders',
            field=models.ManyToManyField(related_name='overrider_levels', through='approval.ApprovalDocumentLevelOverriders', to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvergrouprole',
            name='approver_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvergrouprole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergrouprole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='approvergrouprole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, through='approval.ApproverGroupRole', to='users.role'),
        ),
        migrations.AddField(
            model_name='approvergroupuser',
            name='approver_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approvergroup'),
        ),
        migrations.AddField(
            model_name='approvergroupuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergroupuser',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvergroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='approvergroup',
            name='users',
            field=models.ManyToManyField(blank=True, through='approval.ApproverGroupUser', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='approvaltask',
            unique_together={('approval', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentleveloverriders',
            unique_together={('approval_document_level', 'approver_group')},
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentlevelapprovers',
            unique_together={('approval_document_level', 'approver_group')},
        ),
        migrations.AlterUniqueTogether(
            name='approvaldocumentlevel',
            unique_together={('approval_document', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='approvergroup',
            unique_together={('institution', 'name')},
        ),
    ]
