# Generated by Django 5.2.6 on 2025-10-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_initial'),
        ('projects', '0009_project_completed_status_project_failed_status'),
        ('settings', '0004_taskemailconfig_on_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskemailconfig',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_email_config', to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='taskemailconfig',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_task_email_config', to='projects.project'),
        ),
    ]
