# Generated by Django 5.2.6 on 2025-10-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttaskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttaskstatus',
            name='institution',
        ),
    ]
