# Generated by Django 5.2.6 on 2025-10-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projecttaskstatus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='projects.task'),
        ),
    ]
