# Generated by Django 5.2.6 on 2025-10-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_completed_status', to='projects.projecttaskstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='failed_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_failed_status', to='projects.projecttaskstatus'),
        ),
    ]
