# Generated by Django 5.2.6 on 2025-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_taskstatus_unique_task_status_per_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='freeze_assignee',
            field=models.BooleanField(default=False),
        ),
    ]
