# Generated by Django 5.2.6 on 2025-10-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_projectdiscussionparticipant_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='applied_task_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='failed_status',
        ),
    ]
