from django.urls import path
from .views import (
    ProjectListCreateView,
    ProjectDetailView,
    ProjectStatusDetailView,
    ProjectStatusListCreateView,
    TaskListCreateView,
    TaskTimeSheetView,
    TaskDetailView,
    DashboardAnalyticsView,
    ProjectTaskStatusDetailView,
    TaskPriorityListCreateView,
    TaskPriorityDetailView,
    MainDashboardView,
    ProjectAnalyticsDashboardView,
    TaskAnalyticsDashboardView,
    ProjectUsersApiView,
    ProjectMessageListCreateApiView,
    ProjectMessageDetailApiView,
    TaskMessageListCreateApiView,
    TaskMessageDetailApiView,
    TaskExtensionRequestListCreateView,
    TaskExtensionRequestDetail,
    TaskExtensionRequestApprove,
    TaskExtensionRequestReject,
    ProjectTaskStatusDefaultsView,
    ProjectTaskStatusListView,
    ProjectDiscussionParticipantListCreateApiView,
    ProjectDisscusionParticipantDetailsApiView,
    TaskDisscusionParticipantListCreateApiView,
    TasskDisscusionParticipantDetailsApiView,
    ProjectTaskEmailConfigListCreateView,
    ProjectTaskEmailConfigDetailView,
    ProjectTaskProgressStatus,
)

urlpatterns = [
    path(
        "projects/",
        ProjectListCreateView.as_view(),
        name="project-list-create",
    ),
    path(
        "projects/<int:pk>/details/",
        ProjectDetailView.as_view(),
        name="project-detail",
    ),
    path(
        "tasks/", TaskListCreateView.as_view(), name="task-list-create"
    ),
    path("tasks/<int:pk>/details/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "start-end-task/<int:task_timesheet_id>/",
        TaskTimeSheetView.as_view(),
        name="task-timesheet",
    ),
    path("project-status/", ProjectStatusListCreateView.as_view(), name="project-status"),
    path("project-status/<int:pk>/details/", ProjectStatusDetailView.as_view(), name="project-status-detail"),
    path("analytics/", DashboardAnalyticsView.as_view(), name="dashboard-analytics"),
    path("task-priority/", TaskPriorityListCreateView.as_view(), name="task-priority"),
    path("task-priority/<int:pk>/details/", TaskPriorityDetailView.as_view(), name="task-prioriy-detail"),
    path("dashboard/", MainDashboardView.as_view(), name="dashboard"),
    path("project-analytics/", ProjectAnalyticsDashboardView.as_view(), name="project-analytics"),
    path("task-analytics", TaskAnalyticsDashboardView.as_view(), name="task-analytics"),
    path("users/<int:pk>/", ProjectUsersApiView.as_view(), name="project-users"),
    path("project-messages/", ProjectMessageListCreateApiView.as_view(), name="project-messages"),
    path("project-messages/<int:pk>/", ProjectMessageDetailApiView.as_view(), name="project-message-detail"),
    path("task-messages/", TaskMessageListCreateApiView.as_view(), name="task-messages"),
    path("task-messages/<int:pk>/", TaskMessageDetailApiView.as_view(), name="task-messages-detail"),
    path("task-extension/", TaskExtensionRequestListCreateView.as_view(), name="task-extension"),
    path("task-extension/<int:pk>/", TaskExtensionRequestDetail.as_view(), name="task-extension-detail"),
    path("task-extension/approve/", TaskExtensionRequestApprove.as_view(), name="task-extension-approve"),
    path("task-extension/reject/", TaskExtensionRequestReject.as_view(), name="task-extension-reject"),
    path("default-status/", ProjectTaskStatusDefaultsView.as_view(), name="default-status"),
    path("task-status/", ProjectTaskStatusListView.as_view(), name="project-task-status"),
    path("task-status/<int:pk>/details/", ProjectTaskStatusDetailView.as_view(), name="task-status-detail"),
    path("project-discussion-participant/", ProjectDiscussionParticipantListCreateApiView.as_view(), name="project-discussion-participant"),
    path("project-discussion-participant/<int:pk>/details/", ProjectDisscusionParticipantDetailsApiView.as_view(), name="project-discussion-participant-detial"),
    path("task-discussion-participant/", TaskDisscusionParticipantListCreateApiView.as_view(), name="task-discussion-participant"),
    path("task-discussion-participant/<int:pk>/details/", TasskDisscusionParticipantDetailsApiView.as_view(), name="task-discussion-participant-detail"),
    path("task-config/", ProjectTaskEmailConfigListCreateView.as_view(), name="task-config"),
    path("task-config/<int:pk>/details/", ProjectTaskEmailConfigDetailView.as_view(), name="task-config-detail"),
    path("task-state/", ProjectTaskProgressStatus.as_view(), name="task-state"),
]

