export enum MISC_ACTION_TYPES {
	TOGGLE_SIDEBAR = "misc/TOGGLE_SIDEBAR",
	CLOSE_SIDE_BAR = "misc/CLOSE_SIDE_BAR",
	OPEN_SIDE_BAR = "misc/OPEN_SIDE_BAR",
	SAVE_SELECTED_TASK = "misc/SAVE_SELECTED_TASK",
	CLEAR_SELECTED_TASK = "misc/CLEAR_SELECTED_TASK",
}
